### ISSUE TITLE
Erro partitura

### ISSUE THREAD

**Issue by MottajeffDisco** [marcioyonamine/acervoccsp#58]
Marcio, a vivi me passou um erro no qual ela não consegue editar os registros, no arquivo tem um print das mensagens de erro, bem como os nº de registro dos arquivos.
[Doc1.docx](https://github.com/marcioyonamine/acervoccsp/files/1039568/Doc1.docx)

E a pergy passou que  a função Filtrar por usuário, não está rodando, a partir da segunda página ja começa a misturar os registros com os de outros

**Comment by marcioyonamine** [comment]
Oi Jefferson, estarei no ccsp amanhã e já vejo isso.

abs
